In [2]:
import numpy as np

In [3]:
# Hands on exercise on Numpy

# Array Operations and Broadcasting:

# 1 ) Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.

a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)

result = a * b
print(result)

[[[0.35828917 0.32546794 0.20616551 0.48265176]
  [0.28081465 0.28522109 0.68074714 0.29594648]
  [0.70247333 0.27673574 0.45664929 0.00147533]]

 [[0.09095084 0.0332829  0.13437052 0.35007955]
  [0.08991186 0.43100657 0.22200221 0.54353707]
  [0.62489941 0.28618796 0.75722544 0.00338621]]]


In [8]:
# 2 ) Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division)
# between them using broadcasting. Handle the case where broadcasting is not possible.

def element_wise_operations(c, d):
    try:
        addition = c + d
        subtraction = c - d
        multiplication = c * d
        division = c / d
        return addition, subtraction, multiplication, division
    except ValueError:
        return "Broadcasting not possible "

c = np.random.rand(4, 5)
d = np.random.rand(4, 1)

results = element_wise_operations(c, d)
print(results)



(array([[1.30177867, 1.18681831, 1.60344285, 0.95097506, 0.93884867],
       [1.56908729, 1.27381397, 1.02750545, 1.49301013, 1.48496082],
       [1.69635298, 1.45059451, 1.01879713, 1.64495766, 1.51705312],
       [0.40917909, 0.34513552, 0.1650709 , 0.35518516, 0.69866969]]), array([[-0.06051597, -0.17547633,  0.24114821, -0.41131958, -0.42344597],
       [ 0.25937806, -0.03589526, -0.28220378,  0.1833009 ,  0.17525159],
       [-0.15456753, -0.400326  , -0.83212339, -0.20596285, -0.3338674 ],
       [ 0.16667227,  0.1026287 , -0.07743592,  0.11267834,  0.45616287]]), array([[0.42274138, 0.34443644, 0.62821913, 0.18379244, 0.17553258],
       [0.59868949, 0.40532839, 0.24403212, 0.54887001, 0.54359888],
       [0.71343058, 0.48599088, 0.08637956, 0.66586626, 0.54749568],
       [0.03491197, 0.02714647, 0.00531302, 0.02836502, 0.07001369]]), array([[0.91115583, 0.74238123, 1.35403238, 0.39613712, 0.37833423],
       [1.39608495, 0.94518591, 0.56905887, 1.27991083, 1.26761908],
       

In [9]:
# 3 ) Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.

e = np.random.rand(5, 3)
f = np.random.rand(5)

outer_product = e[:, np.newaxis] * f[:, np.newaxis, np.newaxis]
print(outer_product)


[[[0.49106247 0.27035875 0.32093469]]

 [[0.07726151 0.02572794 0.02392871]]

 [[0.01621241 0.10139826 0.07112884]]

 [[0.27253248 0.40548389 0.36239673]]

 [[0.07734122 0.10049233 0.11157527]]]


In [10]:
# Indexing and Slicing:

# 1 ) Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension.

g = np.random.rand(4, 3, 2)
ans = g[::2, ::2, :]
print(ans)


[[[0.22017386 0.9917521 ]
  [0.70887696 0.12754649]]

 [[0.10246788 0.2702984 ]
  [0.25806051 0.42952986]]]


In [12]:
# 2 ) Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].

def diagonal(h, i, j):
    k = np.array([h[row, col] for row, col in zip(i, j)])
    return k

h = np.random.rand(4, 6)
i = np.array([0, 1, 2])
j = np.array([0, 1, 2])

k = diagonal (h, i, j)
print(k)


[0.22943206 0.7793881  0.28677402]


In [16]:
# 3) Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.

def corresponding_product(l):
    row_means = l.mean(axis=1, keepdims=True)
    col_means = l.mean(axis=0, keepdims=True)
    m = row_means * col_means
    return m

l = np.random.rand(2, 4)
m = corresponding_product(l)
print(m)


[[0.17604328 0.13290017 0.19414904 0.15466451]
 [0.32480797 0.24520695 0.35821394 0.28536315]]


In [18]:
# Array Manipulation:

# 1 ) Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).

n = np.random.rand(4, 6)

n_reshaped = n.reshape(2, 2, 6)
flatten = n_reshaped.reshape(4, 6)
print(n_reshaped)
print(flatten)


[[[0.92178588 0.92204861 0.18777625 0.0661553  0.03072778 0.93504505]
  [0.05477333 0.18708215 0.31816136 0.54248865 0.75020602 0.93972461]]

 [[0.1331908  0.39122445 0.49924996 0.33206479 0.47362093 0.09088396]
  [0.58730134 0.01496801 0.47715526 0.41649142 0.28092578 0.44823447]]]
[[0.92178588 0.92204861 0.18777625 0.0661553  0.03072778 0.93504505]
 [0.05477333 0.18708215 0.31816136 0.54248865 0.75020602 0.93972461]
 [0.1331908  0.39122445 0.49924996 0.33206479 0.47362093 0.09088396]
 [0.58730134 0.01496801 0.47715526 0.41649142 0.28092578 0.44823447]]


In [19]:
# 2 )Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].

def rolls_array(o, positions):
    return np.roll(o, positions, axis=0)

o = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ans = rolls_array(o, 1)
print(ans)


[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [20]:
# 3) Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array.

def replace_with_mean(p, x):
    p = p.copy()
    rows, cols = p.shape
    for i in range(rows):
        for j in range(cols):
            if p[i, j] == x:
                neighbors = []
                if i > 0:
                    neighbors.append(p[i-1, j])
                if i < rows - 1:
                    neighbors.append(p[i+1, j])
                if j > 0:
                    neighbors.append(p[i, j-1])
                if j < cols - 1:
                    neighbors.append(p[i, j+1])
                p[i, j] = np.mean(neighbors)
    return p

p = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 0]])
replaced_p = replace_with_mean(p, 0)
print(replaced_p)



[[1 2 3]
 [4 5 6]
 [7 8 7]]
