In [1]:
pip install numpy

In [3]:
import numpy as np

In [4]:
# To print different types of arrays

# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a.shape)

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)

(5,)
(2, 3)
(2, 2, 2)


In [5]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [6]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a/5)

[50 70 90]
[-30 -30 -30]
[0.25 0.4  0.5 ]
[ 400 1000 1800]
[2. 4. 6.]


In [8]:
a = np.array([27,40,65,90,120,170])
b = np.sqrt(a)
c = np.exp(a)
print(b)
print(c)

[ 5.19615242  6.32455532  8.06225775  9.48683298 10.95445115 13.03840481]
[5.32048241e+11 2.35385267e+17 1.69488924e+28 1.22040329e+39
 1.30418088e+52 6.76179381e+73]


In [14]:
a = np.array([10, 20])
b = np.array([30, 40])

c = np.hstack((a, b))
print(c)

d = np.vstack((a, b))
print(d)

e = np.stack((a, b), axis=1)
print(e)

[10 20 30 40]
[[10 20]
 [30 40]]
[[10 30]
 [20 40]]


In [ ]:
# Splitting arrays
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)

In [11]:
# Time comparison b/w sum of elements in numpy vs in python list
import time

a = np.random.rand(10000000)

start = time.time()
total = np.sum(a)
end = time.time()
print(f"NumPy sum took: {end - start:.6f} seconds")

start = time.time()
x = [i for i in range(10000000)]
total = sum(x)
end = time.time()
print(f"Python list sum took: {end - start:.6f} seconds")


NumPy sum took: 0.008038 seconds
Python list sum took: 0.651422 seconds


In [12]:
# Time comparison b/w mean of elements in numpy vs in python list
import time

a = np.random.rand(10000000)

start = time.time()
total = np.sum(a)
end = time.time()
print(f"NumPy sum took: {end - start:.6f} seconds")

start = time.time()
x = [i for i in range(10000000)]
total = sum(x)
end = time.time()
print(f"Python list sum took: {end - start:.6f} seconds")


NumPy sum took: 0.007142 seconds
Python list sum took: 0.774964 seconds
